"""empty message

Revision ID: cf2a7d8c1428
Revises: 
Create Date: 2016-05-15 22:11:57.459043

"""

# revision identifiers, used by Alembic.
revision = 'cf2a7d8c1428'
down_revision = None
branch_labels = None
depends_on = None

from alembic import context
from alembic import op
import sqlalchemy as sa


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
