"""initial setup

Revision ID: e1d9e941db75
Revises: cf2a7d8c1428
Create Date: 2016-05-15 22:19:16.357657

"""

# revision identifiers, used by Alembic.
revision = 'e1d9e941db75'
down_revision = 'cf2a7d8c1428'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('wizlock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date_created')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    ### end Alembic commands ###
